import HEX_ from "./HEX.js";
import ISOUtil_ from "./ISOUtil.js";
import ISOBody_ from "./ISOBody.js";
import ISOField_ from "./ISOField.js";
import ISOInputStream_ from "./ISOInputStream.js";
import ISOOutputStream_ from "./ISOOutputStream.js";
export declare const HEX: typeof HEX_;
export declare const ISOUtil: typeof ISOUtil_;
export declare const ISOBody: typeof ISOBody_;
export declare const ISOField: typeof ISOField_;
export declare const ISOInputStream: typeof ISOInputStream_;
export declare const ISOOutputStream: typeof ISOOutputStream_;
export declare const FieldDefinition: string;
declare const _default: {
    HEX: typeof HEX_;
    ISOUtil: typeof ISOUtil_;
    FieldDefinition: string;
    ISOBody: typeof ISOBody_;
    ISOField: typeof ISOField_;
    ISOInputStream: typeof ISOInputStream_;
    ISOOutputStream: typeof ISOOutputStream_;
};
export default _default;
